import { EpisodeListSchema, type Episode } from './schema'

/** 12장 여정 — 성탄에서 빈 무덤까지 (GDD §5) */
export const EPISODES: Episode[] = EpisodeListSchema.parse([
  {
    id: 'ep01',
    no: 1,
    title: '고요한 밤',
    subtitle: '별을 따라 베들레헴으로, 거처를 찾아서',
    verb: '추리',
    verseRef: '누가복음 2:1-20',
    companions: ['mary', 'joseph'],
    playable: false,
  },
  {
    id: 'ep02',
    no: 2,
    title: '광야의 소리',
    subtitle: '요단강 "길을 예비하라"',
    verb: '리듬',
    verseRef: '마가복음 1:1-11',
    companions: ['john-baptist'],
    playable: false,
  },
  {
    id: 'ep03',
    no: 3,
    title: '광야',
    subtitle: '싸우지 않고, 영리하게 거절하기',
    verb: '추리',
    verseRef: '마태복음 4:1-11',
    companions: [],
    playable: false,
  },
  {
    id: 'ep04',
    no: 4,
    title: '나를 따르라',
    subtitle: '동료를 모으는 팀 결성의 장',
    verb: '물류',
    verseRef: '마태복음 4:18-22',
    companions: ['peter', 'andrew', 'matthew'],
    playable: false,
  },
  {
    id: 'ep05',
    no: 5,
    title: '산상수훈',
    subtitle: '세상을 뒤집는 가르침, 비네트로',
    verb: '퍼즐',
    verseRef: '마태복음 5-7장',
    companions: [],
    playable: false,
  },
  {
    id: 'ep06',
    no: 6,
    title: '표적과 이적',
    subtitle: '지붕을 뚫어 친구를 내리다',
    verb: '퍼즐',
    verseRef: '마가복음 2:1-12',
    companions: ['healed-friend'],
    playable: false,
  },
  {
    id: 'ep07',
    no: 7,
    title: '모두를 먹이다',
    subtitle: '5천 명, 한 오후, 불어나는 계산',
    verb: '물류',
    verseRef: '요한복음 6:1-14',
    companions: ['philip'],
    playable: false,
  },
  {
    id: 'ep08',
    no: 8,
    title: '내게로 오라',
    subtitle: '빛에서 눈을 떼지 마세요',
    verb: '균형',
    verseRef: '마태복음 14:22-33',
    companions: ['peter'],
    playable: true,
  },
  {
    id: 'ep09',
    no: 9,
    title: '먼 나라',
    subtitle: '탕자·사마리아인·잃은 양을 플레이',
    verb: '추리',
    verseRef: '누가복음 15장',
    companions: ['zacchaeus'],
    playable: false,
  },
  {
    id: 'ep10',
    no: 10,
    title: '나귀 타고 오신 왕',
    subtitle: '종려주일 웨이브, 그리고 성전',
    verb: '리듬',
    verseRef: '마태복음 21:1-17',
    companions: ['nicodemus'],
    playable: false,
  },
  {
    id: 'ep11',
    no: 11,
    title: '마지막 만찬',
    subtitle: '"깨어 있으라" — 곁에 있는 힘',
    verb: '추리',
    verseRef: '요한복음 13장',
    companions: ['john'],
    playable: false,
  },
  {
    id: 'ep12',
    no: 12,
    title: '사흘째 되는 날',
    subtitle: '절제된 함께함, 그리고 빈 무덤',
    verb: '균형',
    verseRef: '누가복음 24장',
    companions: ['mary-magdalene'],
    playable: false,
  },
])

export const getEpisode = (id: string): Episode | undefined =>
  EPISODES.find((e) => e.id === id)
