/* 자리 시네마틱의 장면 정본 — 자리마다 5컷(도착의 문법)과 한/영 자막.
 *
 * 문법(docs/EPISODE-CINEMATICS-PLAN.md §2): 접근 → 도착 → 사건(기존 자리 그림) →
 * 말씀(클로즈업+자막) → 머묾(빛이 바뀐 여운). 자리는 대적이 아니다 — 승리가 아니라
 * 도착과 묵상이다. 이펙트는 mood가 정한다(episode-video.mjs의 MOOD 프리셋 —
 * lament는 빛내림·화이트플래시 금지, 이 파일이 아니라 기계가 강제한다).
 *
 * 말씀: 한글 개역한글(퍼블릭 도메인 — 앱과 동일 판본) · 영어 WEB(World English Bible,
 * 퍼블릭 도메인, 정통 개신교 사용 무리 없음). **본문 인용은 사람 검수 대상**(§4.3 —
 * 성경 본문이 정본이다. 오타·의역이 있으면 여기가 아니라 성경이 이긴다).
 *
 * 지금은 P0 파일럿(예수 · 부르심 5자리). P1에서 33자리, P2에서 101자리로 확장 —
 * 같은 구조로 늘리기만 한다. cut.gen = 생성 파일명(scripts/video-frames/ep/),
 * cut.art = 기존 그림 재사용('st:'=stations, 'ep:'=episodes, 'adv:'=adversaries,
 * 'vf:'=video-frames 루트). */

export const SCENES = [
  {
    id: 'jesus-baptism',
    journey: 'jesus',
    stationId: 'baptism',
    place: '요단강', placeEn: 'The Jordan', title: '세례', titleEn: 'The Baptism',
    mood: 'wonder',
    verse: '이는 내 사랑하는 아들이요\n내 기뻐하는 자라',
    verseEn: 'This is my beloved Son,\nwith whom I am well pleased.',
    ref: '마태복음 3:17 · Matthew 3:17',
    cuts: [
      { gen: 'jesus-baptism-1', prompt: 'the Jordan valley seen from a distance at golden hour, the winding green river line threading between bare pale hills, a thin footpath descending toward the water' },
      { gen: 'jesus-baptism-2', prompt: 'the reed-lined bank of the Jordan River up close, calm green water, smooth worn stones at the waterline where many feet have stood' },
      { art: 'st:baptism.webp' },
      { gen: 'jesus-baptism-4', prompt: 'circles rippling outward on the calm river surface in warm morning light, one white dove flying low over the water', verse: true },
      { gen: 'jesus-baptism-5', prompt: 'the Jordan river bank at dusk, the water a quiet band of fading gold between dark reeds, empty and still' },
    ],
  },
  {
    id: 'jesus-temptation',
    journey: 'jesus',
    stationId: 'temptation',
    place: '광야', placeEn: 'The Wilderness', title: '시험', titleEn: 'The Temptation',
    mood: 'wilderness',
    verse: '사람이 떡으로만 살 것이 아니요\n하나님의 입으로 나오는 모든 말씀으로 살 것이라',
    verseEn: 'Man shall not live by bread alone,\nbut by every word that proceeds\nout of the mouth of God.',
    ref: '마태복음 4:4 · Matthew 4:4',
    /* 광야 컷은 대적 파이프라인이 이미 만들었다 — 재사용, 신규 생성 0 */
    cuts: [
      { art: 'adv:wilderness-40.webp' },
      { art: 'vf:wilderness-stones.webp' },
      { art: 'st:temptation.webp' },
      { art: 'vf:wilderness-night.webp', verse: true },
      { art: 'vf:wilderness-dawn.webp' },
    ],
  },
  {
    id: 'jesus-call-mt4',
    journey: 'jesus',
    stationId: 'call-mt4',
    place: '갈릴리 해변', placeEn: 'Sea of Galilee', title: '첫 부르심', titleEn: 'The Calling',
    mood: 'everyday',
    verse: '나를 따라오라\n내가 너희로 사람을 낚는 어부가 되게 하리라',
    verseEn: 'Come after me, and I will make you\nfishers for men.',
    ref: '마태복음 4:19 · Matthew 4:19',
    cuts: [
      { gen: 'jesus-call-1', prompt: 'the Sea of Galilee seen from low hills at morning, a wide calm band of blue-green water, small fishing boats far out, bare brown hills on the far shore' },
      { gen: 'jesus-call-2', prompt: 'a pebble shore of the Sea of Galilee, two open wooden fishing boats drawn up on the shingle, folded nets piled beside them' },
      { art: 'st:call-mt4.webp' },
      { gen: 'jesus-call-4', prompt: 'a fishing net left lying on wet shingle at the waterline, its ropes trailing toward the calm water, morning light on the mesh', verse: true },
      { gen: 'jesus-call-5', prompt: 'the Galilee shore at dusk, boats as dark shapes against a band of fading gold water, nets left behind on the stones' },
    ],
  },
  {
    id: 'jesus-beat-1',
    journey: 'jesus',
    stationId: 'beat-1',
    place: '팔복산', placeEn: 'Mount of Beatitudes', title: '팔복', titleEn: 'The Beatitudes',
    mood: 'everyday',
    verse: '심령이 가난한 자는 복이 있나니\n천국이 저희 것임이요',
    verseEn: 'Blessed are the poor in spirit,\nfor theirs is the Kingdom of Heaven.',
    ref: '마태복음 5:3 · Matthew 5:3',
    cuts: [
      { gen: 'jesus-beat1-1', prompt: 'a gentle green hill rising above the Sea of Galilee, wildflowers scattered on its slopes, a thin path climbing toward the rounded summit' },
      { gen: 'jesus-beat1-2', prompt: 'the grassy upper slope of the hill, wind bending the wild grasses and scattered red anemones, the wide lake shining far below' },
      { art: 'st:beat-1.webp' },
      { gen: 'jesus-beat1-4', prompt: 'wild red anemones and white lilies close up among bending grasses, soft morning light through the petals', verse: true },
      { gen: 'jesus-beat1-5', prompt: 'the hilltop at golden hour, long soft shadows running down the slope toward the shining lake below' },
    ],
  },
  {
    id: 'jesus-beat-2',
    journey: 'jesus',
    stationId: 'beat-2',
    place: '팔복산', placeEn: 'Mount of Beatitudes', title: '긍휼과 화평', titleEn: 'Mercy and Peace',
    mood: 'compassion',
    verse: '화평케 하는 자는 복이 있나니\n저희가 하나님의 아들이라 일컬음을 받을 것임이요',
    verseEn: 'Blessed are the peacemakers,\nfor they shall be called children of God.',
    ref: '마태복음 5:9 · Matthew 5:9',
    cuts: [
      { gen: 'jesus-beat2-1', prompt: 'terraced slopes below the hill with old olive trees, a worn path passing between low dry-stone walls' },
      { gen: 'jesus-beat2-2', prompt: 'one ancient olive tree on the hillside, its broad shade falling on flat sitting stones, the lake glinting beyond' },
      { art: 'st:beat-2.webp' },
      { gen: 'jesus-beat2-4', prompt: 'two doves resting together on a gnarled olive branch, soft warm light, leaves stirring gently', verse: true },
      { gen: 'jesus-beat2-5', prompt: 'the olive slopes in quiet evening light, the lake below a calm mirror of dusk gold' },
    ],
  },
  {
    id: 'jesus-call-mk1',
    journey: 'jesus',
    stationId: 'call-mk1',
    place: '갈릴리 해변', placeEn: 'Sea of Galilee', title: '어부를 부르시다', titleEn: 'Fishers of Men',
    mood: 'everyday',
    verse: '나를 따라 오너라 내가 너희로\n사람을 낚는 어부가 되게 하리라',
    verseEn: 'Come ye after me, and I will make you\nto become fishers of men.',
    ref: '마가복음 1:17 · Mark 1:17',
    cuts: [
      { gen: 'jesus-call-mk1-1', prompt: 'the Galilee shoreline seen from a coastal path at morning, low waves on the pebble beach, fishing boats scattered along the far curve of the bay' },
      { gen: 'jesus-call-mk1-2', prompt: 'two wooden fishing boats drawn up side by side on the shingle, nets spread out between them over the stones for mending' },
      { art: 'st:call-mk1.webp' },
      { gen: 'jesus-call-mk1-4', prompt: 'a half-mended fishing net spread across smooth shore stones, a wooden netting needle resting in the open mesh, morning light', verse: true },
      { gen: 'jesus-call-mk1-5', prompt: 'the two boats on the shore at dusk, the spread nets left open between them, the lake behind fading to quiet gold' },
    ],
  },
  {
    id: 'jesus-light-mt5',
    journey: 'jesus',
    stationId: 'light-mt5',
    place: '갈릴리', placeEn: 'Galilee', title: '세상의 빛', titleEn: 'Light of the World',
    mood: 'everyday',
    verse: '이같이 너희 빛을 사람 앞에 비취게 하여\n저희로 너희 착한 행실을 보고 하늘에 계신\n너희 아버지께 영광을 돌리게 하라',
    verseEn: 'Let your light so shine before men,\nthat they may see your good works,\nand glorify your Father which is in heaven.',
    ref: '마태복음 5:16 · Matthew 5:16',
    cuts: [
      { gen: 'jesus-light-mt5-1', prompt: 'a hillside village of flat-roofed stone houses seen from the valley path at dusk, warm window lights beginning to show' },
      { gen: 'jesus-light-mt5-2', prompt: 'a narrow village lane at dusk between stone walls, one low wall ahead where a small clay lamp stands ready' },
      { art: 'st:light-mt5.webp' },
      { gen: 'jesus-light-mt5-4', prompt: 'a small clay oil lamp burning on a low stone wall, its flame steady, warm light spilling over the rooftops below', verse: true },
      { gen: 'jesus-light-mt5-5', prompt: 'the village rooftops deep in night, the one lamp still burning on its wall, its glow reaching down the dark lane' },
    ],
  },
  {
    id: 'jesus-lords-prayer',
    journey: 'jesus',
    stationId: 'lords-prayer',
    place: '갈릴리', placeEn: 'Galilee', title: '주기도문', titleEn: 'The Lord’s Prayer',
    mood: 'everyday',
    verse: '나라이 임하옵시며\n뜻이 하늘에서 이룬 것 같이\n땅에서도 이루어지이다',
    verseEn: 'Thy kingdom come. Thy will be done\nin earth, as it is in heaven.',
    ref: '마태복음 6:10 · Matthew 6:10',
    cuts: [
      { gen: 'jesus-lords-prayer-1', prompt: 'a quiet path climbing toward a walled courtyard on a hillside before dawn, the sky wide and paling above' },
      { gen: 'jesus-lords-prayer-2', prompt: 'an open stone courtyard at first light, smooth worn paving, a small clay lamp set on the ground near the centre' },
      { art: 'st:lords-prayer.webp' },
      { gen: 'jesus-lords-prayer-4', prompt: 'a small clay lamp on worn courtyard stones under a wide dawn sky, the paving catching the first pale light', verse: true },
      { gen: 'jesus-lords-prayer-5', prompt: 'the same courtyard at full morning, the lamp out, sunlight lying in a broad band across the paving stones' },
    ],
  },
  {
    id: 'jesus-wise-builder',
    journey: 'jesus',
    stationId: 'wise-builder',
    place: '갈릴리', placeEn: 'Galilee', title: '반석 위의 집', titleEn: 'House on the Rock',
    mood: 'everyday',
    verse: '누구든지 나의 이 말을 듣고 행하는 자는\n그 집을 반석 위에 지은\n지혜로운 사람 같으리니',
    verseEn: 'Whosoever heareth these sayings of mine,\nand doeth them, I will liken him unto\na wise man, which built his house upon a rock.',
    ref: '마태복음 7:24 · Matthew 7:24',
    cuts: [
      { gen: 'jesus-wise-builder-1', prompt: 'a valley after a storm seen from a ridge path, a swollen stream crossing the sand flats, one stone house standing on a rock shelf' },
      { gen: 'jesus-wise-builder-2', prompt: 'the stone house up close on its bare rock foundation, walls square and dry, flood water passing harmlessly below' },
      { art: 'st:wise-builder.webp' },
      { gen: 'jesus-wise-builder-4', prompt: 'the meeting line of bare grey rock and wet sand at the base of a stone wall, the foundation stones firm above the waterline', verse: true },
      { gen: 'jesus-wise-builder-5', prompt: 'the house on the rock at evening after the flood, water withdrawn, warm light on its unmoved walls, the sandy hollow beyond empty' },
    ],
  },
  {
    id: 'jesus-sower',
    journey: 'jesus',
    stationId: 'sower',
    place: '호숫가', placeEn: 'The Lakeside', title: '씨 뿌리는 자', titleEn: 'The Sower',
    mood: 'everyday',
    verse: '더러는 좋은 땅에 떨어지매 혹 백 배,\n혹 육십 배, 혹 삼십 배의 결실을 하였느니라',
    verseEn: 'But other fell into good ground,\nand brought forth fruit, some an hundredfold,\nsome sixtyfold, some thirtyfold.',
    ref: '마태복음 13:8 · Matthew 13:8',
    cuts: [
      { gen: 'jesus-sower-1', prompt: 'lakeside farmland seen from a low rise, a ploughed field sloping toward the water, a footpath running along its edge' },
      { gen: 'jesus-sower-2', prompt: 'the ploughed field up close, its ground changing in bands — a trodden path, shallow stony soil, a thorn patch, deep dark earth' },
      { art: 'st:sower.webp' },
      { gen: 'jesus-sower-4', prompt: 'tall heads of ripe grain standing thick in dark rich soil, heavy with seed, warm light through the stalks', verse: true },
      { gen: 'jesus-sower-5', prompt: 'the field at golden hour, long shadows across the four bands of ground, the grain in the good soil catching the last sun' },
    ],
  },
  {
    id: 'jesus-mustard',
    journey: 'jesus',
    stationId: 'mustard',
    place: '갈릴리', placeEn: 'Galilee', title: '겨자씨', titleEn: 'The Mustard Seed',
    mood: 'everyday',
    verse: '이는 모든 씨보다 작은 것이로되\n자란 후에는 나물보다 커서 나무가 되매\n공중의 새들이 와서 그 가지에 깃들이느니라',
    verseEn: 'When it is grown, it is the greatest among herbs,\nand becometh a tree, so that the birds of the air\ncome and lodge in the branches thereof.',
    ref: '마태복음 13:32 · Matthew 13:32',
    cuts: [
      { gen: 'jesus-mustard-1', prompt: 'a garden plot outside a village seen from the road, one great spreading tree rising above the garden walls' },
      { gen: 'jesus-mustard-2', prompt: 'the base of the great tree inside the garden, wide branches reaching over the wall, small birds moving among the leaves' },
      { art: 'st:mustard.webp' },
      { gen: 'jesus-mustard-4', prompt: 'one tiny mustard seed on a flat stone, the vast trunk of the grown tree rising behind it, birds nesting in the branches above', verse: true },
      { gen: 'jesus-mustard-5', prompt: 'the great tree at dusk as a broad dark silhouette full of roosting birds, the garden quiet beneath its branches' },
    ],
  },
  {
    id: 'jesus-feeding',
    journey: 'jesus',
    stationId: 'feeding',
    place: '벳새다 들녘', placeEn: 'Bethsaida', title: '오병이어', titleEn: 'The Feeding',
    mood: 'wonder',
    verse: '예수께서 떡을 가져 축사하신 후에\n앉은 자들에게 나눠 주시고\n고기도 그렇게 저희의 원대로 주시다',
    verseEn: 'Jesus took the loaves; and when he had\ngiven thanks, he distributed to the disciples,\nand the disciples to them that were set down.',
    ref: '요한복음 6:11 · John 6:11',
    cuts: [
      { gen: 'jesus-feeding-1', prompt: 'a wide grassy hillside above the lake in late afternoon, paths converging across the slopes toward a level green place' },
      { gen: 'jesus-feeding-2', prompt: 'a level place on the green hillside, woven baskets set down on the grass, the lake shining below' },
      { art: 'st:feeding.webp' },
      { gen: 'jesus-feeding-4', prompt: 'five round barley loaves and two fish laid on a woven basket in the grass, afternoon light falling warm across them', verse: true },
      { gen: 'jesus-feeding-5', prompt: 'the hillside at dusk, twelve woven baskets standing full on the darkening grass, the lake below holding the last light' },
    ],
  },
  {
    id: 'jesus-walk-water',
    journey: 'jesus',
    stationId: 'walk-water',
    place: '갈릴리 호숫가', placeEn: 'Sea of Galilee', title: '물 위를 걷다', titleEn: 'Walking on Water',
    mood: 'wonder',
    verse: '안심하라 내니\n두려워 말라',
    verseEn: 'Be of good cheer; it is I;\nbe not afraid.',
    ref: '마태복음 14:27 · Matthew 14:27',
    cuts: [
      { gen: 'jesus-walk-water-1', prompt: 'the lake at night seen from the shore, wind-driven waves silver under a high moon, one small boat far out on the water' },
      { gen: 'jesus-walk-water-2', prompt: 'the small wooden boat among night waves, spray at its bow, moonlight breaking on the water around it' },
      { art: 'st:walk-water.webp' },
      { gen: 'jesus-walk-water-4', prompt: 'a bright path of moonlight running across suddenly stilled water toward the small boat, the waves settling to glass', verse: true },
      { gen: 'jesus-walk-water-5', prompt: 'the lake at earliest dawn, water calm to the horizon, the boat resting near the far shore under a paling sky' },
    ],
  },
  {
    id: 'jesus-take-heart',
    journey: 'jesus',
    stationId: 'take-heart',
    place: '갈릴리 호숫가', placeEn: 'Sea of Galilee', title: '배에 오르시니', titleEn: 'The Wind Ceased',
    mood: 'wonder',
    verse: '배에 있는 사람들이 예수께 절하며 가로되\n진실로 하나님의 아들이로소이다 하더라',
    verseEn: 'They that were in the ship came and worshipped him,\nsaying, Of a truth thou art the Son of God.',
    ref: '마태복음 14:33 · Matthew 14:33',
    cuts: [
      { gen: 'jesus-take-heart-1', prompt: 'storm clouds towering over the lake seen from the eastern hills, a grey curtain of wind and rain moving over the water' },
      { gen: 'jesus-take-heart-2', prompt: 'a small boat sitting on suddenly calm water, its sail loose and still, dark storm clouds drawing back behind it' },
      { art: 'st:take-heart.webp' },
      { gen: 'jesus-take-heart-4', prompt: 'the wooden hull of the boat mirrored perfectly in glass-still water, the last storm cloud lifting from the far hills', verse: true },
      { gen: 'jesus-take-heart-5', prompt: 'the calm lake at evening, clear sky washed after the storm, the boat drawn toward shore under the first stars' },
    ],
  },
  {
    id: 'jesus-blind-sight',
    journey: 'jesus',
    stationId: 'blind-sight',
    place: '실로암', placeEn: 'Siloam', title: '소경이 보다', titleEn: 'The Blind See',
    mood: 'compassion',
    verse: '실로암 못에 가서 씻으라 하시니\n이에 가서 씻고 밝은 눈으로 왔더라',
    verseEn: 'Go, wash in the pool of Siloam.\nHe went his way therefore, and washed,\nand came seeing.',
    ref: '요한복음 9:7 · John 9:7',
    cuts: [
      { gen: 'jesus-blind-sight-1', prompt: 'stone steps descending between city walls toward a rock-cut pool, a shaft of daylight reaching down into the hollow' },
      { gen: 'jesus-blind-sight-2', prompt: 'the still pool of Siloam up close, clear water over pale stone, a small clay jar resting on the worn rim' },
      { art: 'st:blind-sight.webp' },
      { gen: 'jesus-blind-sight-4', prompt: 'clear water in the stone pool with light entering from above, gentle circles spreading from the steps at its edge', verse: true },
      { gen: 'jesus-blind-sight-5', prompt: 'the pool at evening, the water holding the last warm light of the sky, the stone steps empty and wet' },
    ],
  },
  {
    id: 'jesus-transfig',
    journey: 'jesus',
    stationId: 'transfig',
    place: '변화산', placeEn: 'Mount Tabor', title: '변모', titleEn: 'The Transfiguration',
    mood: 'wonder',
    verse: '저희 앞에서 변형되사 그 얼굴이\n해 같이 빛나며 옷이 빛과 같이 희어졌더라',
    verseEn: 'His face did shine as the sun,\nand his raiment was white as the light.',
    ref: '마태복음 17:2 · Matthew 17:2',
    cuts: [
      { gen: 'jesus-transfig-1', prompt: 'Mount Tabor rising rounded and alone above the plain, a thin path winding up its wooded slopes' },
      { gen: 'jesus-transfig-2', prompt: 'the high summit above a low sea of cloud, bare pale rock in white morning light' },
      { art: 'st:transfig.webp' },
      { gen: 'jesus-transfig-4', prompt: 'pale white light flooding the summit rock, three small booths of woven branches standing at its edge above the cloud', verse: true },
      { gen: 'jesus-transfig-5', prompt: 'the summit at dusk as the cloud sinks away, the plain far below in shadow, the path turning down the mountain again' },
    ],
  },
  {
    id: 'jesus-lost-sheep',
    journey: 'jesus',
    stationId: 'lost-sheep',
    place: '유대 들판', placeEn: 'Judea', title: '잃은 양', titleEn: 'The Lost Sheep',
    mood: 'compassion',
    verse: '또 찾은즉 즐거워\n어깨에 메고',
    verseEn: 'And when he hath found it,\nhe layeth it on his shoulders, rejoicing.',
    ref: '누가복음 15:5 · Luke 15:5',
    cuts: [
      { gen: 'jesus-lost-sheep-1', prompt: 'rolling Judean pasture hills at late afternoon, a pale flock gathered on a far hilltop, a narrow track running down toward a ravine' },
      { gen: 'jesus-lost-sheep-2', prompt: 'the mouth of a dark ravine among broom bushes and boulders, the narrow track descending into shadow' },
      { art: 'st:lost-sheep.webp' },
      { gen: 'jesus-lost-sheep-4', prompt: 'one small sheep found among the rocks at the ravine floor, a shepherd staff laid on the stone beside it, soft light reaching down', verse: true },
      { gen: 'jesus-lost-sheep-5', prompt: 'the hills at dusk, the whole flock together again on the high pasture, the ravine below empty and dim' },
    ],
  },
  {
    id: 'jesus-prodigal',
    journey: 'jesus',
    stationId: 'prodigal',
    place: '아버지의 집', placeEn: 'The Father’s House', title: '돌아온 아들', titleEn: 'The Prodigal Son',
    mood: 'compassion',
    verse: '아직도 상거가 먼데 아버지가 저를 보고\n측은히 여겨 달려가 목을 안고 입을 맞추니',
    verseEn: 'When he was yet a great way off, his father saw him,\nand had compassion, and ran, and fell on his neck,\nand kissed him.',
    ref: '누가복음 15:20 · Luke 15:20',
    cuts: [
      { gen: 'jesus-prodigal-1', prompt: 'a long dirt road running between fields toward a distant farmhouse, its doorway standing open at the end of the road' },
      { gen: 'jesus-prodigal-2', prompt: 'the farmhouse courtyard gate flung wide, the door open, a lamp already burning at the doorpost in daylight' },
      { art: 'st:prodigal.webp' },
      { gen: 'jesus-prodigal-4', prompt: 'a fine robe laid ready over a courtyard bench beside a ring and sandals, the open door warm behind them', verse: true },
      { gen: 'jesus-prodigal-5', prompt: 'the farmhouse at night, every window lit for a feast, warm light from the open door reaching far down the dark road' },
    ],
  },
  {
    id: 'jesus-samaritan',
    journey: 'jesus',
    stationId: 'samaritan',
    place: '여리고 길', placeEn: 'The Jericho Road', title: '선한 사마리아인', titleEn: 'The Good Samaritan',
    mood: 'compassion',
    verse: '어떤 사마리아인은 여행하는 중\n거기 이르러 그를 보고 불쌍히 여겨',
    verseEn: 'But a certain Samaritan, as he journeyed,\ncame where he was: and when he saw him,\nhe had compassion on him.',
    ref: '누가복음 10:33 · Luke 10:33',
    cuts: [
      { gen: 'jesus-samaritan-1', prompt: 'the steep road from Jerusalem to Jericho winding down between dry stony hills, long shadows across the passes' },
      { gen: 'jesus-samaritan-2', prompt: 'a bend of the stony road where a bundle lies fallen at the roadside, scattered belongings on the dust' },
      { art: 'st:samaritan.webp' },
      { gen: 'jesus-samaritan-4', prompt: 'a flask of oil and a flask of wine set on the road stones beside torn cloth bindings, a patient donkey standing near', verse: true },
      { gen: 'jesus-samaritan-5', prompt: 'an inn at nightfall further down the road, its courtyard lamp lit, the donkey resting at the gate, the dark hills behind' },
    ],
  },
  {
    id: 'jesus-resurrection-hope',
    journey: 'jesus',
    stationId: 'resurrection-hope',
    place: '베다니', placeEn: 'Bethany', title: '나는 부활이요', titleEn: 'I Am the Resurrection',
    mood: 'wonder',
    verse: '나는 부활이요 생명이니\n나를 믿는 자는 죽어도 살겠고',
    verseEn: 'I am the resurrection, and the life:\nhe that believeth in me, though he were dead,\nyet shall he live.',
    ref: '요한복음 11:25 · John 11:25',
    cuts: [
      { gen: 'jesus-resurrection-hope-1', prompt: 'the village of Bethany on the slope of the Mount of Olives, flat-roofed houses among olive trees, a path arriving from the east' },
      { gen: 'jesus-resurrection-hope-2', prompt: 'a rock-cut doorway in the hillside near the village, one old olive tree standing beside it, quiet daylight' },
      { art: 'st:resurrection-hope.webp' },
      { gen: 'jesus-resurrection-hope-4', prompt: 'warm light falling across the stone threshold of the rock-cut doorway, green olive leaves alive above the sill', verse: true },
      { gen: 'jesus-resurrection-hope-5', prompt: 'the hillside doorway at dawn, first light reaching deep past the threshold, dew bright on the olive tree' },
    ],
  },
  {
    id: 'jesus-lazarus-come',
    journey: 'jesus',
    stationId: 'lazarus-come',
    place: '베다니', placeEn: 'Bethany', title: '나사로야 나오라', titleEn: 'Lazarus, Come Forth',
    mood: 'wonder',
    verse: '이 말씀을 하시고 큰 소리로\n나사로야 나오라 부르시니',
    verseEn: 'He cried with a loud voice,\nLazarus, come forth.',
    ref: '요한복음 11:43 · John 11:43',
    cuts: [
      { gen: 'jesus-lazarus-come-1', prompt: 'a path leaving the village toward burial caves in the hillside, quiet olive groves, a rock face ahead' },
      { gen: 'jesus-lazarus-come-2', prompt: 'the tomb mouth up close, the great round stone rolled back from the opening, daylight entering the rock chamber' },
      { art: 'st:lazarus-come.webp' },
      { gen: 'jesus-lazarus-come-4', prompt: 'folded linen grave cloths lying on the tomb threshold, light from outside reaching across them into the emptied dark', verse: true },
      { gen: 'jesus-lazarus-come-5', prompt: 'the open tomb at evening, the rolled stone at rest against the rock, the path back to the village lit by low sun' },
    ],
  },
  {
    id: 'jesus-entry',
    journey: 'jesus',
    stationId: 'entry',
    place: '예루살렘', placeEn: 'Jerusalem', title: '입성', titleEn: 'The Entry',
    mood: 'everyday',
    verse: '호산나 다윗의 자손이여 찬송하리로다\n주의 이름으로 오시는 이여\n가장 높은 곳에서 호산나',
    verseEn: 'Hosanna to the Son of David:\nBlessed is he that cometh in the name of the Lord;\nHosanna in the highest.',
    ref: '마태복음 21:9 · Matthew 21:9',
    cuts: [
      { gen: 'jesus-entry-1', prompt: 'Jerusalem seen from the descending Mount of Olives road, city walls and gates golden in morning light' },
      { gen: 'jesus-entry-2', prompt: 'the road rising to the city gate, palm branches and cloaks strewn thick across the stones ahead' },
      { art: 'st:entry.webp' },
      { gen: 'jesus-entry-4', prompt: 'fresh-cut palm branches lying layered over spread cloaks on the paving stones before the open gate', verse: true },
      { gen: 'jesus-entry-5', prompt: 'the gate road at dusk, the scattered palm branches stilled on the empty stones, the city walls darkening above' },
    ],
  },
  {
    id: 'jesus-talents',
    journey: 'jesus',
    stationId: 'talents',
    place: '감람산', placeEn: 'Mount of Olives', title: '달란트', titleEn: 'The Talents',
    mood: 'everyday',
    verse: '잘 하였도다 착하고 충성된 종아\n네가 작은 일에 충성하였으매\n내가 많은 것으로 네게 맡기리니',
    verseEn: 'Well done, thou good and faithful servant:\nthou hast been faithful over a few things,\nI will make thee ruler over many things.',
    ref: '마태복음 25:21 · Matthew 25:21',
    cuts: [
      { gen: 'jesus-talents-1', prompt: 'an olive-terraced hillside with a low farmstead among the trees, a path climbing between dry-stone walls' },
      { gen: 'jesus-talents-2', prompt: 'a plain wooden table set under an olive tree in the farm court, cloth pouches and an open scroll upon it' },
      { art: 'st:talents.webp' },
      { gen: 'jesus-talents-4', prompt: 'two full cloth pouches of silver coins open on the wooden table, and beside the table a small pit of earth with a third pouch half-buried', verse: true },
      { gen: 'jesus-talents-5', prompt: 'the farm court at evening, lamplight warm on the table where the pouches lie counted, the olive trees dark beyond' },
    ],
  },
  {
    id: 'jesus-last-supper',
    journey: 'jesus',
    stationId: 'last-supper',
    place: '다락방', placeEn: 'The Upper Room', title: '최후의 만찬', titleEn: 'The Last Supper',
    mood: 'everyday',
    verse: '예수께서 떡을 가지사 축복하시고 떼어\n제자들을 주시며 가라사대\n받아 먹으라 이것이 내 몸이니라',
    verseEn: 'Jesus took bread, and blessed it, and brake it,\nand gave it to the disciples, and said,\nTake, eat; this is my body.',
    ref: '마태복음 26:26 · Matthew 26:26',
    cuts: [
      { gen: 'jesus-last-supper-1', prompt: 'a narrow stone stairway climbing the outside of a Jerusalem house at evening, a lit doorway waiting at the top' },
      { gen: 'jesus-last-supper-2', prompt: 'the upper room within, a long low table laid with places, oil lamps burning low along the walls' },
      { art: 'st:last-supper.webp' },
      { gen: 'jesus-last-supper-4', prompt: 'a round loaf broken in two beside a single clay cup of wine on the table linen, lamplight close and warm', verse: true },
      { gen: 'jesus-last-supper-5', prompt: 'the upper room late at night, the places empty, the broken bread and cup still on the table, one lamp left burning' },
    ],
  },
  {
    id: 'jesus-gethsemane',
    journey: 'jesus',
    stationId: 'gethsemane',
    place: '겟세마네', placeEn: 'Gethsemane', title: '동산의 기도', titleEn: 'The Garden Prayer',
    mood: 'lament',
    verse: '내 아버지여 만일 내가 마시지 않고는\n이 잔이 내게서 지나갈 수 없거든\n아버지의 원대로 되기를 원하나이다',
    verseEn: 'O my Father, if this cup may not pass away from me,\nexcept I drink it, thy will be done.',
    ref: '마태복음 26:42 · Matthew 26:42',
    cuts: [
      { gen: 'jesus-gethsemane-1', prompt: 'the Kidron valley crossed at night, a dim path climbing toward a walled olive grove under heavy clouds' },
      { gen: 'jesus-gethsemane-2', prompt: 'the olive grove within, ancient twisted trunks in deep shadow, one small lamp burning low on the ground' },
      { art: 'st:gethsemane.webp' },
      { gen: 'jesus-gethsemane-4', prompt: 'a heavy stone olive press among the dark trunks, oil dripping slow into the basin, the small lamp flame nearly still', verse: true },
      { gen: 'jesus-gethsemane-5', prompt: 'the grove in the last dark before dawn, the lamp out, grey cloud shadow lying over the silent trees' },
    ],
  },
  {
    id: 'jesus-arrest',
    journey: 'jesus',
    stationId: 'arrest',
    place: '기드론', placeEn: 'The Kidron', title: '잡히심', titleEn: 'The Arrest',
    mood: 'lament',
    verse: '저희가 예수께\n손을 대어 잡거늘',
    verseEn: 'And they laid their hands on him,\nand took him.',
    ref: '마가복음 14:46 · Mark 14:46',
    cuts: [
      { gen: 'jesus-arrest-1', prompt: 'the dark Kidron ravine at night, a cold stream threading between black rocks, low clouds hiding the stars' },
      { gen: 'jesus-arrest-2', prompt: 'torches burning between the ravine walls at night, hard shadows thrown across the stones' },
      { art: 'st:arrest.webp' },
      { gen: 'jesus-arrest-4', prompt: 'a single dropped cloak lying on the trampled ground, a fallen torch guttering out beside it in the dark', verse: true },
      { gen: 'jesus-arrest-5', prompt: 'the ravine empty in the deep of night, the torches gone, only the cold stream moving between the stones' },
    ],
  },
  {
    id: 'jesus-pilate',
    journey: 'jesus',
    stationId: 'pilate',
    place: '가바다', placeEn: 'Gabbatha', title: '빌라도 앞에서', titleEn: 'Before Pilate',
    mood: 'lament',
    verse: '이에 예수께서 가시 면류관을 쓰고\n자색 옷을 입고 나오시니 빌라도가\n저희에게 말하되 보라 이 사람이로다 하매',
    verseEn: 'Then came Jesus forth, wearing the crown of thorns,\nand the purple robe. And Pilate saith unto them,\nBehold the man!',
    ref: '요한복음 19:5 · John 19:5',
    cuts: [
      { gen: 'jesus-pilate-1', prompt: 'the fortress walls of the Praetorium at grey first light, a stone ramp rising to the pavement court, sky overcast' },
      { gen: 'jesus-pilate-2', prompt: 'the raised stone pavement wide and bare, columns casting long cold shadows across the flags' },
      { art: 'st:pilate.webp' },
      { gen: 'jesus-pilate-4', prompt: 'the bare judgment seat up close in flat grey light, ancient game circles scored into the worn pavement stones before it', verse: true },
      { gen: 'jesus-pilate-5', prompt: 'the pavement at dusk emptied, wind moving dust across the stones between the long column shadows' },
    ],
  },
  {
    id: 'jesus-golgotha',
    journey: 'jesus',
    stationId: 'golgotha',
    place: '골고다', placeEn: 'Golgotha', title: '십자가', titleEn: 'The Cross',
    mood: 'lament',
    verse: '아버지여 저희를 사하여 주옵소서\n자기의 하는 것을 알지 못함이니이다',
    verseEn: 'Father, forgive them;\nfor they know not what they do.',
    ref: '누가복음 23:34 · Luke 23:34',
    cuts: [
      { gen: 'jesus-golgotha-1', prompt: 'a road leading out of the city gate under a darkening noon sky, a bare rounded hill rising beyond the wall' },
      { gen: 'jesus-golgotha-2', prompt: 'the rocky top of the bare hill under low dark cloud, three empty post sockets cut into the stone' },
      { art: 'st:golgotha.webp' },
      { gen: 'jesus-golgotha-4', prompt: 'a plain folded garment and small marked pebbles cast as lots lying on the bare rock, the light low and grey', verse: true },
      { gen: 'jesus-golgotha-5', prompt: 'the hill in mid-afternoon darkness, the city walls dim behind, cloud shadow covering the bare rock' },
    ],
  },
  {
    id: 'jesus-finished',
    journey: 'jesus',
    stationId: 'finished',
    place: '골고다', placeEn: 'Golgotha', title: '다 이루었다', titleEn: 'It Is Finished',
    mood: 'lament',
    verse: '다 이루었다 하시고\n머리를 숙이시고 영혼이 돌아가시니라',
    verseEn: 'It is finished:\nand he bowed his head, and gave up the ghost.',
    ref: '요한복음 19:30 · John 19:30',
    cuts: [
      { gen: 'jesus-finished-1', prompt: 'the bare hill outside the wall under a sky gone dark at midday, the city silent beyond' },
      { gen: 'jesus-finished-2', prompt: 'a jar of sour wine and a hyssop reed left at the foot of the rocks, the light failing' },
      { art: 'st:finished.webp' },
      { gen: 'jesus-finished-4', prompt: 'the heavy woven temple curtain torn in two from top to bottom, its edges hanging still in the dim air', verse: true },
      { gen: 'jesus-finished-5', prompt: 'the bare hill at evening, the sky beginning to clear at the horizon, everything still' },
    ],
  },
  {
    id: 'jesus-cross-luke',
    journey: 'jesus',
    stationId: 'cross-luke',
    place: '골고다', placeEn: 'Golgotha', title: '아버지 손에', titleEn: 'Into Thy Hands',
    mood: 'lament',
    verse: '아버지여 내 영혼을\n아버지 손에 부탁하나이다',
    verseEn: 'Father, into thy hands\nI commend my spirit.',
    ref: '누가복음 23:46 · Luke 23:46',
    cuts: [
      { gen: 'jesus-cross-luke-1', prompt: 'darkness over the whole land at midday, the sun failed behind deep cloud, the hill and city gone dim' },
      { gen: 'jesus-cross-luke-2', prompt: 'the bare hill in the strange dark, outlines of rock and wall barely showing, all quiet' },
      { art: 'st:cross-luke.webp' },
      { gen: 'jesus-cross-luke-4', prompt: 'one small lamp flame burning low and unwavering against the great darkness over the land', verse: true },
      { gen: 'jesus-cross-luke-5', prompt: 'evening over the quiet hill, one single point of pale light low on the horizon, the land released from the dark' },
    ],
  },
  {
    id: 'jesus-empty-tomb',
    journey: 'jesus',
    stationId: 'empty-tomb',
    place: '동산 무덤', placeEn: 'The Garden Tomb', title: '빈 무덤', titleEn: 'The Empty Tomb',
    mood: 'joy',
    verse: '그가 여기 계시지 않고\n그의 말씀하시던 대로 살아나셨느니라\n와서 그의 누우셨던 곳을 보라',
    verseEn: 'He is not here: for he is risen, as he said.\nCome, see the place where the Lord lay.',
    ref: '마태복음 28:6 · Matthew 28:6',
    cuts: [
      { gen: 'jesus-empty-tomb-1', prompt: 'a garden path in the grey of earliest dawn, dew on the leaves, a rock face ahead where a tomb is cut' },
      { gen: 'jesus-empty-tomb-2', prompt: 'the tomb at first light, the great round stone rolled aside, the dark doorway standing open' },
      { art: 'st:empty-tomb.webp' },
      { gen: 'jesus-empty-tomb-4', prompt: 'inside the tomb, the stone shelf empty, linen cloths lying folded, dawn light reaching in through the open door', verse: true },
      { gen: 'jesus-empty-tomb-5', prompt: 'full morning over the garden, the open tomb behind, the path bright with early sun leading back toward the city' },
    ],
  },
  {
    id: 'jesus-risen',
    journey: 'jesus',
    stationId: 'risen',
    place: '다락방', placeEn: 'The Upper Room', title: '부활하신 주', titleEn: 'The Risen Lord',
    mood: 'joy',
    verse: '너희에게 평강이 있을지어다\n아버지께서 나를 보내신 것 같이\n나도 너희를 보내노라',
    verseEn: 'Peace be unto you: as my Father hath sent me,\neven so send I you.',
    ref: '요한복음 20:21 · John 20:21',
    cuts: [
      { gen: 'jesus-risen-1', prompt: 'a Jerusalem lane at evening, shuttered houses, an outside stair climbing to one closed upper door' },
      { gen: 'jesus-risen-2', prompt: 'the closed upper-room door up close, warm light pressing through every gap around its frame' },
      { art: 'st:risen.webp' },
      { gen: 'jesus-risen-4', prompt: 'warm light filling the upper room, the lamps steady, bread and fish set on the table, the barred door glowing at every seam', verse: true },
      { gen: 'jesus-risen-5', prompt: 'the upper room door at dawn standing open, morning light down the stairway, the lane below waking' },
    ],
  },
  {
    id: 'jesus-commission',
    journey: 'jesus',
    stationId: 'commission',
    place: '갈릴리 산', placeEn: 'Galilee', title: '지상명령', titleEn: 'The Great Commission',
    mood: 'joy',
    verse: '너희는 가서\n모든 족속으로 제자를 삼아',
    verseEn: 'Go ye therefore,\nand teach all nations.',
    ref: '마태복음 28:19 · Matthew 28:19',
    cuts: [
      { gen: 'jesus-commission-1', prompt: 'a path climbing a Galilean mountain in bright morning, the lake and hills spreading wider with every turn' },
      { gen: 'jesus-commission-2', prompt: 'the broad mountain top under open sky, paths running out from it in every direction toward distant horizons' },
      { art: 'st:commission.webp' },
      { gen: 'jesus-commission-4', prompt: 'the paths from the summit reaching toward far lands and seas at the horizon, morning light on every road', verse: true },
      { gen: 'jesus-commission-5', prompt: 'the mountain at evening, the many paths glowing faintly with the last sun, each one leading out toward the ends of the earth' },
    ],
  },
]

/* episode-art.mjs와 동일 스캐폴드 — 한 앱 안에서 룩이 갈리면 안 된다. 저쪽 수정 시 동기화 */
export const SCAFFOLD =
  'flat geometric illustration, a single square vignette for a Christian pilgrimage running app. ' +
  'Warm golden-hour Holy Land palette only: sand cream #f4ead7, terracotta clay #c05a30, olive sage #6e7a4c, ' +
  'sun-gold #e0a53f, deep umber #2c2118. Clean geometric shapes, flat fills, soft two-tone shading, ' +
  'subtle warm paper grain. One clear subject, centred, bold simple silhouette. ' +
  'A square composition that completely fills the square canvas corner to corner. Colour and texture ' +
  'reach every one of the four corners. Ancient Near East world. ' +
  'Show the place itself, empty and still, no people. ' +
  'NO depiction of Jesus, NO ring or disc or arc behind anything, NO religious icons, NO crucifix ornament, ' +
  'NO outlines, NO ink linework, NO text, NO letters, NO watermark, NO neon, NO photorealism, NO clip-art. Subject: '
